// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bdlim1_gaussian_cpp
Rcpp::List bdlim1_gaussian_cpp(const arma::vec& y, arma::u64 nits, const arma::mat& design, bool REmodel, double REprec, arma::u64 nRE, arma::u64 n_regcoef);
RcppExport SEXP _bdlim_bdlim1_gaussian_cpp(SEXP ySEXP, SEXP nitsSEXP, SEXP designSEXP, SEXP REmodelSEXP, SEXP REprecSEXP, SEXP nRESEXP, SEXP n_regcoefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::u64 >::type nits(nitsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< bool >::type REmodel(REmodelSEXP);
    Rcpp::traits::input_parameter< double >::type REprec(REprecSEXP);
    Rcpp::traits::input_parameter< arma::u64 >::type nRE(nRESEXP);
    Rcpp::traits::input_parameter< arma::u64 >::type n_regcoef(n_regcoefSEXP);
    rcpp_result_gen = Rcpp::wrap(bdlim1_gaussian_cpp(y, nits, design, REmodel, REprec, nRE, n_regcoef));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bdlim_bdlim1_gaussian_cpp", (DL_FUNC) &_bdlim_bdlim1_gaussian_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_bdlim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
