# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdlim1_gaussian_cpp <- function(y, design_input, nits, REmodel, nRE, w_group_ids, basis, w_input, theta_input, Edesign, exposure) {
    .Call(`_bdlim_bdlim1_gaussian_cpp`, y, design_input, nits, REmodel, nRE, w_group_ids, basis, w_input, theta_input, Edesign, exposure)
}

bdlim1_logistic_cpp <- function(y, design_input, nits, REmodel, nRE, w_group_ids, basis, w_input, theta_input, Edesign, exposure) {
    .Call(`_bdlim_bdlim1_logistic_cpp`, y, design_input, nits, REmodel, nRE, w_group_ids, basis, w_input, theta_input, Edesign, exposure)
}

