# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdlim1_gaussian_cpp <- function(y, design, nits, REmodel, nRE, REprec, w_group_ids, Edesign, basis, w, theta, exposure) {
    .Call(`_bdlim_bdlim1_gaussian_cpp`, y, design, nits, REmodel, nRE, REprec, w_group_ids, Edesign, basis, w, theta, exposure)
}

bdlim1_logistic_cpp <- function(y, design, nits, REmodel, nRE, REprec, w_group_ids, Edesign, basis, w, theta, exposure) {
    .Call(`_bdlim_bdlim1_logistic_cpp`, y, design, nits, REmodel, nRE, REprec, w_group_ids, Edesign, basis, w, theta, exposure)
}

