# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdlim1_gaussian_cpp <- function(y, nits, design, REmodel, REprec, nRE, n_regcoef) {
    .Call(`_bdlim_bdlim1_gaussian_cpp`, y, nits, design, REmodel, REprec, nRE, n_regcoef)
}

